name: CICD
on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build
        run: |
          docker build -t darlanalves/crosstool-ng .
          docker push darlanalves/crosstool-ng:${{ github.sha }}

      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: docker push darlanalves/crosstool-ng
